name: Deploy site to Pages

on:
  discussion:
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ToPages
        run: |
            git clone https://github.com/ThreeTenth/GitHub-Discussions-to-Blog
            cd GitHub-Discussions-to-Blog
            go get -v -u -d ./...
            if [ -f Gopkg.toml ]; then
                curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                dep ensure
            fi
            ls -a -lh
            echo "GO GET SUCCESSED"
            cat go.mod            
            cat go.sum
            echo "NEXT"
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true
          cache-dependency-path: GitHub-Discussions-to-Blog/go.sum
      - name: Build site
        run: |
            cd GitHub-Discussions-to-Blog
            ls -a -lh
            go build --ldflags="-w -s"
            ls -a -lh
            cd ..
            chmod 775 ./GitHub-Discussions-to-Blog/io.github.topages
            path="abc/def"
            repository=${{ github.repository }}
            repositoryName=$(basename "$repository")
            pagesPath="./"
            baseURL="/$repositoryName"
            gamID="${{ vars.GAMID }}"
            echo "${{ github.repository_owner }}, $repositoryName, ${{secrets.GITHUB_TOKEN}}, $pagesPath, $baseURL, $gamID,"
            ./GitHub-Discussions-to-Blog/io.github.topages -owner ${{ github.repository_owner }} -name $repositoryName  -token ${{secrets.GITHUB_TOKEN}} -pages $pagesPath -baseURL $baseURL -gamID $gamID
            rm -rf ./GitHub-Discussions-to-Blog
            ls -a -lh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
