name: Deploy site to Pages

on:
  discussion:
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ToPages
        run: |
            git clone https://github.com/ThreeTenth/GitHub-Discussions-to-Blog
            cd GitHub-Discussions-to-Blog
            go get -v -u -d ./...
            if [ -f Gopkg.toml ]; then
                curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                dep ensure
            fi
            ls -a -lh
            cat go.sum
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true
      - name: Build site
        run: |
            cd GitHub-Discussions-to-Blog
            ls -a -lh
            go build --ldflags="-w -s"
            ls -a -lh
            cd ..
            chmod 775 ./toPages/io.github.topages
            ./toPages/io.github.topages -owner ${{ github.actor }} -name ${{ github.repository_name }}  -token ${{secrets.GITHUB_TOKEN}} -pages ./
            rm -rf ./toPages
      - name: Commit
        run: |
            git add .
            git commit -m "Update site"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
